name: autofix.ci

on:
  - pull_request

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Lint & fix
      run: npx eslint --ext .js,.vue src build docs/.vitepress --fix
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: ${{ github.ref_name }}-autofix
        reviewers: ${{ github.actor }}
        labels: autofix
        delete-branch: true
        title: "Improve codestyle"
        body: "Automated PR to improve codestyle"