name: autofix.ci

on:
  pull_request:
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: 📥 Install deps
        run: yarn

      - name: Lint
        run: yarn run lint:fix

      - uses: autofix-ci/action@bee19d72e71787c12ca0f29de72f2833e437e4c9