name: autofix.ci

on:
  - pull_request

jobs:
  autofix:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    steps:
      - uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: 📥 Install deps
        run: yarn

      - name: Lint
        run: yarn run lint:fix

      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc