on:
  workflow_dispatch:

name: npm-publish
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'suralabs' }}
    steps:
      - uses: actions/checkout@v3
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: 📥 Install deps
        run: yarn
      - run: yarn run docs:build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}