name: publish npm

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
        branches:
          - main

jobs:
  deploy_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: 📥 Install deps
        run: yarn
      - name: Build dist
        run: yarn run dist
      - name: Publish NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}