name: publish github

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: change package name
        uses: deef0000dragon1/json-edit-action@v1
        env:
          KEY: name
          VALUE: "vancedvue"
          FILE: package.json
      - name: 📥 Install deps
        run: yarn
      - name: Build dist
        run: yarn run dist
      - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} >> .npmrc
      - run: yarn publish --registry=https://npm.pkg.github.com
