name: Release

on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    outputs:
      created: ${{ steps.release.outputs.created }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Release
        id: release
        uses: fdiesel/github-action-node-release@v4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix:  # (optional) default none
          path: ./package.json # (optional) default ./package.json
  deploy_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: 📥 Install deps
        run: yarn
      - name: Build dist
        run: yarn run dist
      - name: Publish NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}          